In [5]:
import pandas as pd

df = pd.read_csv("C:/CSP584PROJCT/zipcacodecsv.csv")
df2=pd.read_csv("C:/CSP584PROJCT/Building_temp.csv")

C:\Users\ajayr\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (1,90,91,92,93,94,95,96,97,98,110) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [8]:
df3=df2[["PERMIT#","PERMIT_TYPE","APPLICATION_START_DATE","ISSUE_DATE","LATITUDE","LONGITUDE"]]

In [22]:
df3["APPLICATION_START_DATE"]=df3["APPLICATION_START_DATE"].astype('datetime64[ns]')
df3=df3.sort_values('APPLICATION_START_DATE', ascending=False)
maindf=df3[:1000]
maindf

,PERMIT#,PERMIT_TYPE,APPLICATION_START_DATE,ISSUE_DATE,LATITUDE,LONGITUDE,zipcode
4072,100851296,PERMIT - NEW CONSTRUCTION,2021-11-30,11/30/2021,41.863984893,-87.62589624200001,
4067,100946087,PERMIT - NEW CONSTRUCTION,2021-11-29,11/29/2021,41.926131428000005,-87.65955069299999,
4070,100927168,PERMIT - NEW CONSTRUCTION,2021-11-29,11/29/2021,41.877553304,-87.69540032799999,
4059,100930670,PERMIT - NEW CONSTRUCTION,2021-11-24,11/24/2021,41.929955219,-87.667251494,
4053,100949303,PERMIT - NEW CONSTRUCTION,2021-11-23,11/23/2021,41.973263744,-87.73917547299999,
...,...,...,...,...,...,...,...
267,100908916,PERMIT - NEW CONSTRUCTION,2021-03-18,03/18/2021,41.858381599,-87.642035131,60616
3992,100909502,PERMIT - NEW CONSTRUCTION,2021-03-18,09/01/2021,41.856156227,-87.656517354,
1867,100909368,PERMIT - NEW CONSTRUCTION,2021-03-18,10/14/2021,41.774410666,-87.594664094,
25118,100908721,PERMIT - NEW CONSTRUCTION,2021-03-17,03/17/2021,41.676730645999996,-87.639612079,
3230,100910472,PERMIT - NEW CONSTRUCTION,2021-03-17,08/05/2021,41.85015478,-87.633496191,

In [23]:
from geopy.geocoders import Nominatim
maindf["zipcode"]=""
#df3 = df3.astype(str)
#df = df.astype(str)
#geolocator = Nominatim(user_agent="geoapiExercises")


for i in range(len(maindf)) :    
    Latitude=str(maindf.iloc[i, 4])
    Longitude=str(maindf.iloc[i, 5])
    
    if Latitude!="nan" and Longitude!="nan":

        location = geolocator.reverse(Latitude+","+Longitude)
        address = location.raw['address']
        zipcode = address.get('postcode')
        #print(dzipcode)
        maindf.iloc[i,6]=zipcode

<ipython-input-23-9d13719c83b2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  maindf["zipcode"]=""
C:\Users\ajayr\Anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [27]:
df4 = pd.read_csv("C:/CSP584PROJCT/zip_ca.csv")
df4

     zipcode   communityareas
0      60647          HERMOSA
1      60619          PULLMAN
2      60625       NORTH PARK
3      60616  NEAR SOUTH SIDE
4      60649         WOODLAWN
..       ...              ...
198    60654             LOOP
199    60618         AVONDALE
200    60666            OHARE
201    60657         LAKEVIEW
202    60638           MIDWAY

[203 rows x 2 columns]

In [29]:
maindf["community_area"]=""
maindf = maindf.astype(str)
df4 = df4.astype(str)

for i in range(len(maindf)) : 
    for j in range(len(df4)) : 
        #print(i,j)
        if maindf.iloc[i,6]==df4.iloc[j,0]:
            #print("j")
            maindf.iloc[i,7]=df4.iloc[j,1]

<ipython-input-29-934fd8ea3dd3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  maindf["community_area"]=""

j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j
j

In [30]:
maindf

,PERMIT#,PERMIT_TYPE,APPLICATION_START_DATE,ISSUE_DATE,LATITUDE,LONGITUDE,zipcode,community_area
4072,100851296,PERMIT - NEW CONSTRUCTION,2021-11-30,11/30/2021,41.863984893,-87.62589624200001,IL,
4067,100946087,PERMIT - NEW CONSTRUCTION,2021-11-29,11/29/2021,41.926131428000005,-87.65955069299999,60614,LOGAN SQUARE
4070,100927168,PERMIT - NEW CONSTRUCTION,2021-11-29,11/29/2021,41.877553304,-87.69540032799999,60644,AUSTIN
4059,100930670,PERMIT - NEW CONSTRUCTION,2021-11-24,11/24/2021,41.929955219,-87.667251494,60614,LOGAN SQUARE
4053,100949303,PERMIT - NEW CONSTRUCTION,2021-11-23,11/23/2021,41.973263744,-87.73917547299999,60630,FOREST GLEN
...,...,...,...,...,...,...,...,...
267,100908916,PERMIT - NEW CONSTRUCTION,2021-03-18,03/18/2021,41.858381599,-87.642035131,60616,ARMOUR SQUARE
3992,100909502,PERMIT - NEW CONSTRUCTION,2021-03-18,09/01/2021,41.856156227,-87.656517354,60608,NORTH LAWNDALE
1867,100909368,PERMIT - NEW CONSTRUCTION,2021-03-18,10/14/2021,41.774410666,-87.594664094,60637,WOODLAWN
25118,100908721,PERMIT - NEW CONSTRUCTION,2021-03-17,03/17/2021,41.676730645999996,-87.639612079,60628,WASHINGTON HEIGHTS
3230,100910472,PERMIT - NEW CONSTRUCTION,2021-03-17,08/05/2021,41.85015478,-87.633496191,60616,ARMOUR SQUARE

In [31]:
maindf.to_csv('building_main.csv')

In [42]:
df10 = pd.read_csv("C:/CSP584PROJCT/zip.csv")
df20 = pd.read_csv("C:/CSP584PROJCT/poverty.csv")
df20

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
0,1,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39
1,2,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46
2,3,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20
3,4,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17
4,5,North Center,0.3,7.5,5.2,4.5,26.2,57123,6
...,...,...,...,...,...,...,...,...,...
72,73,Washington Height,1.1,16.9,20.8,13.7,42.6,19713,48
73,74,Mount Greenwood,1.0,3.4,8.7,4.3,36.8,34381,16
74,75,Morgan Park,0.8,13.2,15.0,10.8,40.3,27149,30
75,76,O'Hare,3.6,15.4,7.1,10.9,30.3,25828,24
76,77,Edgewater,4.1,18.2,9.2,9.7,23.8,33385,19

In [43]:
df10["CHGOCA"] = df10["CHGOCA"].astype(int)
df20["Community Area Number"] = df20["Community Area Number"].astype(int)
df20["zipcode"]=""
for i in range(len(df20)) : 
    for j in range(len(df10)) : 
        #print(i,j)
        if df20.iloc[i,0]==df10.iloc[j,1]:
            #print("j")
            df20.iloc[i,9]=df10.iloc[j,0]

In [44]:
df20

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX,zipcode
0,1,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39,60660
1,2,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46,60660
2,3,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20,60640
3,4,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17,60660
4,5,North Center,0.3,7.5,5.2,4.5,26.2,57123,6,60657
...,...,...,...,...,...,...,...,...,...,...
72,73,Washington Height,1.1,16.9,20.8,13.7,42.6,19713,48,60643
73,74,Mount Greenwood,1.0,3.4,8.7,4.3,36.8,34381,16,60655
74,75,Morgan Park,0.8,13.2,15.0,10.8,40.3,27149,30,60655
75,76,O'Hare,3.6,15.4,7.1,10.9,30.3,25828,24,60706
76,77,Edgewater,4.1,18.2,9.2,9.7,23.8,33385,19,60660

In [45]:
df20.to_csv('poverty_main.csv')

In [49]:
df_tx=pd.read_csv("C:/CSP584PROJCT/Taxi_Trips_2021.csv')

In [51]:
df_tx=df_tx.sort_values('Trip Start Timestamp', ascending=False)

In [57]:
df_tx

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,...,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
3072476,fce82c138a421fd6e2a837845c988d97dadfae9a,961d0f7585bf4b5b5e6a35acea78a36dee71cab2323ab1...,11/01/2021 12:00:00 AM,11/01/2021 12:30:00 AM,2341.0,18.53,NaN,NaN,76.0,1.0,...,4.0,51.00,Credit Card,Flash Cab,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),42.009623,-87.670167,POINT (-87.6701668569 42.0096228806)
3072448,20e190ff86f2206d23efe6f622022c80a68c8cb4,e2252e4d7dd9d448ee731c06e763dbef7fbbc169bc0f67...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,1560.0,9.60,NaN,NaN,8.0,5.0,...,0.0,76.50,Credit Card,Blue Ribbon Taxi Association Inc.,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.947792,-87.683835,POINT (-87.6838349425 41.9477915865)
3072455,44438cc73e9224d06863cd8c81ac92e14179296d,26a53f41b40ca4ec225a15ff55054c0a2d9e4a48341ce9...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,1500.0,0.00,NaN,NaN,76.0,NaN,...,27.5,73.50,Cash,Taxi Affiliation Services,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN
3072454,3f85a2bf34222ba39d9e8cfceaf24ed31685d5a9,df88e40cac8cf5e7da7fe4f619933719098adf6fe05741...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,1200.0,0.00,NaN,NaN,56.0,32.0,...,4.0,33.50,Cash,Taxi Affiliation Services,41.792592,-87.769615,POINT (-87.7696154528 41.7925923603),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841)
3072453,3ddb2f0ea882e2d2d63fe4ee4f08c95687d218c0,f98ae5e71fdda8806710af321dce58002146886c013f41...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,1253.0,10.15,NaN,NaN,76.0,NaN,...,6.0,33.25,Cash,Globe Taxi,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,1b3860ed6eeb0e6c0ecc8f29f12926656da07f7b,b4ac2893286a7c3a55df851a3732ea65d7fb82e1da7a19...,01/01/2021 01:00:00 AM,01/01/2021 01:45:00 AM,2595.0,9.65,NaN,NaN,70.0,68.0,...,0.0,33.50,Prcard,City Service,41.745758,-87.708366,POINT (-87.7083657043 41.7457577128),41.777196,-87.642498,POINT (-87.6424975271 41.7771962546)
87,0b4955dbf03575ec3b7406a65f14c8963f3d4f3a,3f365e125eb1d15aae0ae8a4bf53a01191478f26ccf00c...,01/01/2021 01:00:00 AM,01/01/2021 01:15:00 AM,590.0,1.12,NaN,NaN,14.0,14.0,...,1.0,12.75,Credit Card,Flash Cab,41.968069,-87.721559,POINT (-87.7215590627 41.968069),41.968069,-87.721559,POINT (-87.7215590627 41.968069)
86,0472813b2adc49432007444d585556472f1ae04b,175a58299af3a8c883453259b9a0cfc45ccbbbe1a07883...,01/01/2021 01:00:00 AM,01/01/2021 01:15:00 AM,574.0,1.40,NaN,NaN,8.0,32.0,...,2.0,12.00,Credit Card,Medallion Leasin,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841)
94,983177225eb98bf27fecb1dfd88401b604c0454a,3665a72ee495b03f4dae72307dc6e5e58e21518f77d8e6...,01/01/2021 01:00:00 AM,01/01/2021 01:00:00 AM,480.0,2.10,NaN,NaN,16.0,15.0,...,0.0,8.50,Cash,Taxi Affiliation Services,41.953582,-87.723452,POINT (-87.7234523905 41.9535821253),41.954028,-87.763399,POINT (-87.7633990316 41.9540276487)
93,7262542c5ce97bc2f990ea77899aee8e67f89654,00752524a4118a162dce62ff49c0eb0f79530d9e0ecb5a...,01/01/2021 01:00:00 AM,01/01/2021 01:15:00 AM,1140.0,12.50,NaN,NaN,56.0,24.0,...,4.0,35.50,Credit Card,Taxi Affiliation Services,41.792592,-87.769615,POINT (-87.7696154528 41.7925923603),41.901207,-87.676356,POINT (-87.6763559892 41.9012069941)

In [63]:
df_tx_main=df_tx[:500000]

In [64]:
df_tx_main

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,...,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
3072476,fce82c138a421fd6e2a837845c988d97dadfae9a,961d0f7585bf4b5b5e6a35acea78a36dee71cab2323ab1...,11/01/2021 12:00:00 AM,11/01/2021 12:30:00 AM,2341.0,18.53,NaN,NaN,76.0,1.0,...,4.0,51.00,Credit Card,Flash Cab,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),42.009623,-87.670167,POINT (-87.6701668569 42.0096228806)
3072448,20e190ff86f2206d23efe6f622022c80a68c8cb4,e2252e4d7dd9d448ee731c06e763dbef7fbbc169bc0f67...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,1560.0,9.60,NaN,NaN,8.0,5.0,...,0.0,76.50,Credit Card,Blue Ribbon Taxi Association Inc.,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.947792,-87.683835,POINT (-87.6838349425 41.9477915865)
3072455,44438cc73e9224d06863cd8c81ac92e14179296d,26a53f41b40ca4ec225a15ff55054c0a2d9e4a48341ce9...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,1500.0,0.00,NaN,NaN,76.0,NaN,...,27.5,73.50,Cash,Taxi Affiliation Services,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN
3072454,3f85a2bf34222ba39d9e8cfceaf24ed31685d5a9,df88e40cac8cf5e7da7fe4f619933719098adf6fe05741...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,1200.0,0.00,NaN,NaN,56.0,32.0,...,4.0,33.50,Cash,Taxi Affiliation Services,41.792592,-87.769615,POINT (-87.7696154528 41.7925923603),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841)
3072453,3ddb2f0ea882e2d2d63fe4ee4f08c95687d218c0,f98ae5e71fdda8806710af321dce58002146886c013f41...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,1253.0,10.15,NaN,NaN,76.0,NaN,...,6.0,33.25,Cash,Globe Taxi,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575594,55b2be64229b6b6534be37623908b1d901a34e16,5f395c33ef34f1545aa60c48463f313795e1d872ea9acc...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,1428.0,17.01,NaN,1.703108e+10,NaN,8.0,...,4.0,55.50,Credit Card,Flash Cab,NaN,NaN,NaN,41.893216,-87.637844,POINT (-87.6378442095 41.8932163595)
2575588,512a07e4f09cbb9074f3cdbe82c5058d5697ec32,dff8b2296e1abd3c3470a2f0765b3f385f9a53c8df1cc3...,09/30/2021 09:30:00 PM,09/30/2021 09:45:00 PM,671.0,4.60,NaN,NaN,NaN,NaN,...,1.0,15.00,Cash,Chicago Independents,NaN,NaN,NaN,NaN,NaN,NaN
2575589,5182f5e8dd786307fda78ac4a7b6a8b371444ae3,c7cc8a8dd5c3f7358d0f48468702ebd3a8fe989dfa9ee2...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,780.0,0.10,1.703198e+10,1.703177e+10,76.0,NaN,...,4.5,15.50,Cash,Taxi Affiliation Services,41.979071,-87.903040,POINT (-87.9030396611 41.9790708201),41.982775,-87.877305,POINT (-87.8773053996 41.9827750091)
2575590,530b25a350c9ca6667cfff7ead215ff4b7a06b30,ec4b4f2f183bf84a4a4bd5b8df2ce0f94b98c05c06cb1a...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,0.0,0.00,NaN,NaN,2.0,2.0,...,0.0,3.25,Cash,"Taxicab Insurance Agency, LLC",42.001571,-87.695013,POINT (-87.6950125892 42.001571027),42.001571,-87.695013,POINT (-87.6950125892 42.001571027)
2575591,549fd3bcf842ddd433fe65d8b9f14a610c96d111,a46aedb114a720df392300b351493f1a65cd0e8f485f70...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,1571.0,17.50,1.703198e+10,1.703132e+10,76.0,32.0,...,5.0,58.50,Credit Card,Flash Cab,41.979071,-87.903040,POINT (-87.9030396611 41.9790708201),41.884987,-87.620993,POINT (-87.6209929134 41.8849871918)

In [72]:
import numpy as np
df_tx_main=df_tx_main.replace(np.nan, 0)
df_tx_main["Pickup Community Area"] = df_tx_main["Pickup Community Area"].astype(int)

In [75]:
df_tx_main=df_tx_main.replace(np.nan, 0)
df_tx_main["Dropoff Community Area"] = df_tx_main["Dropoff Community Area"].astype(int)

In [78]:
df_ca = pd.read_csv("C:/CSP584PROJCT/zipcacodecsv.csv")
df_ca

    zip                  CA  Unnamed: 2  Unnamed: 3
0     1         ROGERS PARK         NaN         NaN
1     2          WEST RIDGE         NaN         NaN
2     3              UPTOWN         NaN         NaN
3     4      LINCOLN SQUARE         NaN         NaN
4     5        NORTH CENTER         NaN         NaN
..  ...                 ...         ...         ...
72   73  WASHINGTON HEIGHTS         NaN         NaN
73   74     MOUNT GREENWOOD         NaN         NaN
74   75         MORGAN PARK         NaN         NaN
75   76               OHARE         NaN         NaN
76   77           EDGEWATER         NaN         NaN

[77 rows x 4 columns]

In [81]:
df_tx_main2=df_tx_main[["Trip ID","Taxi ID","Trip Start Timestamp","Trip End Timestamp","Trip Miles","Pickup Community Area","Dropoff Community Area","Trip Total","Company"]]
df_tx_main2

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Miles,Pickup Community Area,Dropoff Community Area,Trip Total,Company
3072476,fce82c138a421fd6e2a837845c988d97dadfae9a,961d0f7585bf4b5b5e6a35acea78a36dee71cab2323ab1...,11/01/2021 12:00:00 AM,11/01/2021 12:30:00 AM,18.53,76,1,51.00,Flash Cab
3072448,20e190ff86f2206d23efe6f622022c80a68c8cb4,e2252e4d7dd9d448ee731c06e763dbef7fbbc169bc0f67...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,9.60,8,5,76.50,Blue Ribbon Taxi Association Inc.
3072455,44438cc73e9224d06863cd8c81ac92e14179296d,26a53f41b40ca4ec225a15ff55054c0a2d9e4a48341ce9...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,0.00,76,0,73.50,Taxi Affiliation Services
3072454,3f85a2bf34222ba39d9e8cfceaf24ed31685d5a9,df88e40cac8cf5e7da7fe4f619933719098adf6fe05741...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,0.00,56,32,33.50,Taxi Affiliation Services
3072453,3ddb2f0ea882e2d2d63fe4ee4f08c95687d218c0,f98ae5e71fdda8806710af321dce58002146886c013f41...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,10.15,76,0,33.25,Globe Taxi
...,...,...,...,...,...,...,...,...,...
2575594,55b2be64229b6b6534be37623908b1d901a34e16,5f395c33ef34f1545aa60c48463f313795e1d872ea9acc...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,17.01,0,8,55.50,Flash Cab
2575588,512a07e4f09cbb9074f3cdbe82c5058d5697ec32,dff8b2296e1abd3c3470a2f0765b3f385f9a53c8df1cc3...,09/30/2021 09:30:00 PM,09/30/2021 09:45:00 PM,4.60,0,0,15.00,Chicago Independents
2575589,5182f5e8dd786307fda78ac4a7b6a8b371444ae3,c7cc8a8dd5c3f7358d0f48468702ebd3a8fe989dfa9ee2...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,0.10,76,0,15.50,Taxi Affiliation Services
2575590,530b25a350c9ca6667cfff7ead215ff4b7a06b30,ec4b4f2f183bf84a4a4bd5b8df2ce0f94b98c05c06cb1a...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,0.00,2,2,3.25,"Taxicab Insurance Agency, LLC"
2575591,549fd3bcf842ddd433fe65d8b9f14a610c96d111,a46aedb114a720df392300b351493f1a65cd0e8f485f70...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,17.50,76,32,58.50,Flash Cab

In [82]:
%%time
df_ca["zip"] = df_ca["zip"].astype(int)
df_tx_main2["pick_ca"]=""
df_tx_main2["drop_ca"]=""
for i in range(len(df_tx_main2)) : 
    for j in range(len(df_ca)) : 
        #print(i,j)
        if df_tx_main2.iloc[i,5]==df_ca.iloc[j,0]:
            #print("j")
            df_tx_main2.iloc[i,9]=df_ca.iloc[j,1]
        if df_tx_main2.iloc[i,6]==df_ca.iloc[j,0]:
            #print("j")
            df_tx_main2.iloc[i,10]=df_ca.iloc[j,1]

<timed exec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<timed exec>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\ajayr\Anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

Wall time: 2h 35min 31s

In [83]:
df_tx_main2

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Miles,Pickup Community Area,Dropoff Community Area,Trip Total,Company,pick_ca,drop_ca
3072476,fce82c138a421fd6e2a837845c988d97dadfae9a,961d0f7585bf4b5b5e6a35acea78a36dee71cab2323ab1...,11/01/2021 12:00:00 AM,11/01/2021 12:30:00 AM,18.53,76,1,51.00,Flash Cab,OHARE,ROGERS PARK
3072448,20e190ff86f2206d23efe6f622022c80a68c8cb4,e2252e4d7dd9d448ee731c06e763dbef7fbbc169bc0f67...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,9.60,8,5,76.50,Blue Ribbon Taxi Association Inc.,NEAR NORTH SIDE,NORTH CENTER
3072455,44438cc73e9224d06863cd8c81ac92e14179296d,26a53f41b40ca4ec225a15ff55054c0a2d9e4a48341ce9...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,0.00,76,0,73.50,Taxi Affiliation Services,OHARE,
3072454,3f85a2bf34222ba39d9e8cfceaf24ed31685d5a9,df88e40cac8cf5e7da7fe4f619933719098adf6fe05741...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,0.00,56,32,33.50,Taxi Affiliation Services,GARFIELD RIDGE,LOOP
3072453,3ddb2f0ea882e2d2d63fe4ee4f08c95687d218c0,f98ae5e71fdda8806710af321dce58002146886c013f41...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,10.15,76,0,33.25,Globe Taxi,OHARE,
...,...,...,...,...,...,...,...,...,...,...,...
2575594,55b2be64229b6b6534be37623908b1d901a34e16,5f395c33ef34f1545aa60c48463f313795e1d872ea9acc...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,17.01,0,8,55.50,Flash Cab,,NEAR NORTH SIDE
2575588,512a07e4f09cbb9074f3cdbe82c5058d5697ec32,dff8b2296e1abd3c3470a2f0765b3f385f9a53c8df1cc3...,09/30/2021 09:30:00 PM,09/30/2021 09:45:00 PM,4.60,0,0,15.00,Chicago Independents,,
2575589,5182f5e8dd786307fda78ac4a7b6a8b371444ae3,c7cc8a8dd5c3f7358d0f48468702ebd3a8fe989dfa9ee2...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,0.10,76,0,15.50,Taxi Affiliation Services,OHARE,
2575590,530b25a350c9ca6667cfff7ead215ff4b7a06b30,ec4b4f2f183bf84a4a4bd5b8df2ce0f94b98c05c06cb1a...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,0.00,2,2,3.25,"Taxicab Insurance Agency, LLC",WEST RIDGE,WEST RIDGE
2575591,549fd3bcf842ddd433fe65d8b9f14a610c96d111,a46aedb114a720df392300b351493f1a65cd0e8f485f70...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,17.50,76,32,58.50,Flash Cab,OHARE,LOOP

In [84]:
df_tx_main2.to_csv('taxi_pred.csv')

In [85]:
df_tx_main2=df_tx_main2.rename(columns={"Trip ID": "trip_id", "Taxi ID": "taxi_id"})

In [86]:
df_tx_main2

,trip_id,taxi_id,Trip Start Timestamp,Trip End Timestamp,Trip Miles,Pickup Community Area,Dropoff Community Area,Trip Total,Company,pick_ca,drop_ca
3072476,fce82c138a421fd6e2a837845c988d97dadfae9a,961d0f7585bf4b5b5e6a35acea78a36dee71cab2323ab1...,11/01/2021 12:00:00 AM,11/01/2021 12:30:00 AM,18.53,76,1,51.00,Flash Cab,OHARE,ROGERS PARK
3072448,20e190ff86f2206d23efe6f622022c80a68c8cb4,e2252e4d7dd9d448ee731c06e763dbef7fbbc169bc0f67...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,9.60,8,5,76.50,Blue Ribbon Taxi Association Inc.,NEAR NORTH SIDE,NORTH CENTER
3072455,44438cc73e9224d06863cd8c81ac92e14179296d,26a53f41b40ca4ec225a15ff55054c0a2d9e4a48341ce9...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,0.00,76,0,73.50,Taxi Affiliation Services,OHARE,
3072454,3f85a2bf34222ba39d9e8cfceaf24ed31685d5a9,df88e40cac8cf5e7da7fe4f619933719098adf6fe05741...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,0.00,56,32,33.50,Taxi Affiliation Services,GARFIELD RIDGE,LOOP
3072453,3ddb2f0ea882e2d2d63fe4ee4f08c95687d218c0,f98ae5e71fdda8806710af321dce58002146886c013f41...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,10.15,76,0,33.25,Globe Taxi,OHARE,
...,...,...,...,...,...,...,...,...,...,...,...
2575594,55b2be64229b6b6534be37623908b1d901a34e16,5f395c33ef34f1545aa60c48463f313795e1d872ea9acc...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,17.01,0,8,55.50,Flash Cab,,NEAR NORTH SIDE
2575588,512a07e4f09cbb9074f3cdbe82c5058d5697ec32,dff8b2296e1abd3c3470a2f0765b3f385f9a53c8df1cc3...,09/30/2021 09:30:00 PM,09/30/2021 09:45:00 PM,4.60,0,0,15.00,Chicago Independents,,
2575589,5182f5e8dd786307fda78ac4a7b6a8b371444ae3,c7cc8a8dd5c3f7358d0f48468702ebd3a8fe989dfa9ee2...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,0.10,76,0,15.50,Taxi Affiliation Services,OHARE,
2575590,530b25a350c9ca6667cfff7ead215ff4b7a06b30,ec4b4f2f183bf84a4a4bd5b8df2ce0f94b98c05c06cb1a...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,0.00,2,2,3.25,"Taxicab Insurance Agency, LLC",WEST RIDGE,WEST RIDGE
2575591,549fd3bcf842ddd433fe65d8b9f14a610c96d111,a46aedb114a720df392300b351493f1a65cd0e8f485f70...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,17.50,76,32,58.50,Flash Cab,OHARE,LOOP

In [87]:
df_tx_main2=df_tx_main2.rename(columns={"Trip Start Timestamp": "trip_start_timestamp", "Trip End Timestamp": "trip_end_timestamp","Trip Miles": "trip_miles","Pickup Community Area": "pickup_community_area","Dropoff Community Area": "dropoff_community_area","Trip Total": "trip_total",})

In [88]:
df_tx_main2=df_tx_main2.rename(columns={"Company": "company",})

In [89]:
df_tx_main2

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_miles,pickup_community_area,dropoff_community_area,trip_total,company,pick_ca,drop_ca
3072476,fce82c138a421fd6e2a837845c988d97dadfae9a,961d0f7585bf4b5b5e6a35acea78a36dee71cab2323ab1...,11/01/2021 12:00:00 AM,11/01/2021 12:30:00 AM,18.53,76,1,51.00,Flash Cab,OHARE,ROGERS PARK
3072448,20e190ff86f2206d23efe6f622022c80a68c8cb4,e2252e4d7dd9d448ee731c06e763dbef7fbbc169bc0f67...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,9.60,8,5,76.50,Blue Ribbon Taxi Association Inc.,NEAR NORTH SIDE,NORTH CENTER
3072455,44438cc73e9224d06863cd8c81ac92e14179296d,26a53f41b40ca4ec225a15ff55054c0a2d9e4a48341ce9...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,0.00,76,0,73.50,Taxi Affiliation Services,OHARE,
3072454,3f85a2bf34222ba39d9e8cfceaf24ed31685d5a9,df88e40cac8cf5e7da7fe4f619933719098adf6fe05741...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,0.00,56,32,33.50,Taxi Affiliation Services,GARFIELD RIDGE,LOOP
3072453,3ddb2f0ea882e2d2d63fe4ee4f08c95687d218c0,f98ae5e71fdda8806710af321dce58002146886c013f41...,11/01/2021 12:00:00 AM,11/01/2021 12:15:00 AM,10.15,76,0,33.25,Globe Taxi,OHARE,
...,...,...,...,...,...,...,...,...,...,...,...
2575594,55b2be64229b6b6534be37623908b1d901a34e16,5f395c33ef34f1545aa60c48463f313795e1d872ea9acc...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,17.01,0,8,55.50,Flash Cab,,NEAR NORTH SIDE
2575588,512a07e4f09cbb9074f3cdbe82c5058d5697ec32,dff8b2296e1abd3c3470a2f0765b3f385f9a53c8df1cc3...,09/30/2021 09:30:00 PM,09/30/2021 09:45:00 PM,4.60,0,0,15.00,Chicago Independents,,
2575589,5182f5e8dd786307fda78ac4a7b6a8b371444ae3,c7cc8a8dd5c3f7358d0f48468702ebd3a8fe989dfa9ee2...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,0.10,76,0,15.50,Taxi Affiliation Services,OHARE,
2575590,530b25a350c9ca6667cfff7ead215ff4b7a06b30,ec4b4f2f183bf84a4a4bd5b8df2ce0f94b98c05c06cb1a...,09/30/2021 09:30:00 PM,09/30/2021 09:30:00 PM,0.00,2,2,3.25,"Taxicab Insurance Agency, LLC",WEST RIDGE,WEST RIDGE
2575591,549fd3bcf842ddd433fe65d8b9f14a610c96d111,a46aedb114a720df392300b351493f1a65cd0e8f485f70...,09/30/2021 09:30:00 PM,09/30/2021 10:00:00 PM,17.50,76,32,58.50,Flash Cab,OHARE,LOOP

In [90]:
df_tx_main2.to_csv('taxi_pred_m.csv')